USE customers_behivours;

-- select * from customers limit 4;
-- 1>what is the total revnue generated by male vs female empolyee.?
-- SELECT gender, SUM(purchase_amount) as total_revenue
-- FROM customers
-- GROUP BY gender

-- 2>which customer used the discount but still spent more then the average purchase amount.? 
-- select customer_id , purchase_amount , discount_applied from customers
-- having discount_applied='yes'
-- AND purchase_amount>(select avg(purchase_amount) from customers);

-- SELECT COUNT(DISTINCT customer_id) AS total_customers
-- FROM customers
-- WHERE discount_applied = 'Yes'
--   AND purchase_amount > (
--       SELECT AVG(purchase_amount)
--       FROM customers
--   );

-- 3> which are the top 5 product with the highest average review rating.?
-- select item_purchased , avg(review_rating) as avg_review_rating  from customers
-- group by item_purchased
-- ORDER BY avg_review_rating DESC
-- LIMIT 5;

-- 4> compare the average purchase amount between standard and express shipping.?
-- SELECT shipping_type,
--        AVG(purchase_amount) AS avg_purchase_amount
-- FROM customers
-- WHERE shipping_type IN ('Standard', 'Express')
-- GROUP BY shipping_type;

-- 5> do subscribed spend more ? compare average spend and total revenue between subscribed and non-subscribers.
-- select subscription_status, avg(purchase_amount),sum(purchase_amount)
-- from customers
-- group by subscription_status

-- SELECT 
-- CASE
-- WHEN (
-- SELECT AVG(purchase_amount) FROM customers
-- WHERE subscription_status='Yes') > (SELECT AVG(purchase_amount) FROM customers WHERE subscription_status='No')
-- THEN 'YES'
-- ELSE 'NO' END 
-- AS who_spend_more 

-- 6>which 5 products have the highest percentage of purchases with discount applied.?
--  select item_purchased , count(*) as total_purchases,
--  count(CASE WHEN discount_applied ='Yes' THEN 1 END ) AS discount_purchases,
--  count(CASE WHEN discount_applied = 'Yes' THEN 1 END ) * 100.0/COUNT(*) AS discount_percentage
--  FROM customers
--  GROUP BY item_purchased
--  ORDER BY discount_purchases DESC
--  LIMIT 5;

-- 7> segment customers new , returning and loyal based on there total number of pervious purchases , and show the count of each segment
-- select 
-- CASE WHEN previous_purchases<15 THEN 'NEW' 
--     WHEN previous_purchases<=20 THEN 'returning'
-- ELSE 'loayl'
-- END AS customer_segment,
-- count(*) as customer_count
-- from customers
-- group by customer_segment

-- 8> what are the top 3 most purchased products within each catagory?
-- SELECT category,
--        item_purchased,
--        COUNT(*) AS purchase_count
-- FROM customers
-- GROUP BY category, item_purchased
-- ORDER BY purchase_count DESC
-- LIMIT 3

--  with item_counts as (
--  select category ,item_purchased ,
--  count(customer_id) as total_orders,
--  row_number() over (partition by category order by count(customer_id) DESC ) as item_rank
--  from customers
--  group by category , item_purchased )
--  select item_rank , category , item_purchased , total_orders
--  from item_counts
--  where item_rank <=3

-- 9> revenue generation by each age group .?
-- SELECT agr_group , sum(purchase_amount) AS total_purchases from customers
-- group by agr_group
-- order by total_purchases DESC


